[".config/nvim"]
type = "git-repo"
url = "git@gitlab.com:schnow265/nvim.conf.git"
refreshPeriod = "24h"

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmuxpack/tpack.git"
refreshPeriod = "168h"

[".local/share/tmuxinator-projects"]
type = "git-repo"
url = "git@gitlab.com:schnow265/tmuxinator-projects.git"
refreshPeriod = "12h"

[".local/share/external/zsh/completions/_tmuxinator"]
type = "file"
url = "https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.zsh"
refreshPeriod = "168h"

[".local/share/external/zsh/completions/_asdf"]
type = "file"
url = "https://raw.githubusercontent.com/asdf-vm/asdf/refs/heads/master/internal/completions/asdf.zsh"
refreshPeriod = "168h"

[".local/share/external/zsh/nixos-completions"]
type = "git-repo"
url = "https://github.com/nix-community/nix-zsh-completions.git"
refreshPeriod = "168h"

[".config/emacs"]
type = "git-repo"
url = "https://github.com/doomemacs/core"
refreshPeriod = "168h"
