[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmuxpack/tpack.git"
refreshPeriod = "168h"

[".local/share/external/zsh/completions/_tmuxinator"]
type = "file"
url = "https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.zsh"
refreshPeriod = "168h"

[".local/share/external/zsh/completions/_asdf"]
type = "file"
url = "https://raw.githubusercontent.com/asdf-vm/asdf/refs/heads/master/internal/completions/asdf.zsh"
refreshPeriod = "168h"

[".local/share/external/zsh/nixos-completions"]
type = "git-repo"
url = "https://github.com/nix-community/nix-zsh-completions.git"
refreshPeriod = "168h"

[".config/emacs"]
type = "git-repo"
url = "https://github.com/plexus/chemacs2.git"
refreshPeriod = "168h"

[".local/share/external/emacs-cfg/doom"]
type = "git-repo"
url = "https://github.com/doomemacs/core"
refreshPeriod = "168h"

[".local/share/external/emacs-cfg/spacemacs"]
type = "git-repo"
url = "https://github.com/syl20bnr/spacemacs.git"
refreshPeriod = "168h"
