setw -g mouse on
set -g status on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin '27medkamal/tmux-session-wizard'
set -g @plugin 'erikw/tmux-powerline'

set -g status-justify left
set -g status-left ""
set -g status-left-length 100
set -g status-right-length 100
set -g status-interval 2

run '~/.tmux/plugins/tpm/tpm'
