categories:
    - name: News
      desc: News from around the world
      subscriptions:
        - name: ORF.at
          desc: ""
          url: https://rss.orf.at/news.xml
    - name: Tech News
      desc: Specifically Tech news

    - name: Release Feeds
      desc: Releases that I follow
      subscriptions:
        - name: Linux Kernel
          desc: "The Linux Kernel Release Feed"
          url: https://www.kernel.org/feeds/kdist.xml
        - name: tmux
          desc: "A Terminal MUltipleXer"
          url: https://github.com/tmux/tmux/releases.atom
        - name: nix
          desc: The purley functional package manager
          url: https://github.com/NixOS/nix/tags.atom
        - name: yabai
          desc: A tiling WM for macOS
          url: https://github.com/koekeishiya/yabai/releases.atom
        - name: WSL2 Linux Kernel
          desc: "The MS Linux Kernel Fork for WSL2"
          url: https://github.com/microsoft/WSL2-Linux-Kernel/releases.atom
        - name: nvm
          desc: "Node Version Manager"
          url: https://github.com/nvm-sh/nvm/releases.atom
        - name: systemD
          desc: "The systemd System and Service Manager"
          url: https://github.com/systemd/systemd/releases.atom
        - name: kmon
          desc: "The Linux Kernel Manager and Activity Monitor"
          url: https://github.com/orhun/kmon/releases.atom
        - name: sdkman-cli
          desc: "The Java-based SDK manager"
          url: https://github.com/sdkman/sdkman-cli/releases.atom
        - name: apx
          desc: The VanillaOS Package Manager
          url: https://github.com/Vanilla-OS/apx/releases.atom
        - name: Stellarium
          desc: "Stellarium is a free GPL software which renders realistic skies in real time with OpenGL."
          url: https://github.com/Stellarium/stellarium/releases.atom
        - name: manim
          desc: "A community-maintained Python framework for creating mathematical animations."
          url: https://github.com/ManimCommunity/manim/releases.atom
        - name: Insomnia
          desc: "The open-source, cross-platform API client for GraphQL, REST, WebSockets, SSE and gRPC. With Cloud, Local and Git storage."
          url: https://github.com/Kong/insomnia/releases.atom
        - name: immich
          desc: "High performance self-hosted photo and video management solution."
          url: https://github.com/immich-app/immich/releases.atom
        - name: slides
          desc: "Terminal based presentation tool"
          url: https://github.com/maaslalani/slides/releases.atom
        - name: Floorp
          desc: "the most Advanced and Fastest Firefox derivative"
          url: https://github.com/Floorp-Projects/Floorp/releases.atom
        - name: ollama
          desc: "Get up and running with Llama 3.1, Mistral, Gemma 2, and other large language models. Locally."
          url: https://github.com/ollama/ollama/releases.atom
        - name: maven
          desc: "Apache Maven is a software project management and comprehension tool"
          url: https://github.com/apache/maven/releases.atom
        - name: rsync
          desc: "An open source utility that provides fast incremental file transfer."
          url: https://github.com/RsyncProject/rsync/tags.atom
        - name: lazygit
          desc: "simple terminal UI for git commands"
          url: https://github.com/jesseduffield/lazygit/releases.atom


    - name: Hermitcraft
      desc: The (in my opinion) most plesant Minecraft multiplayer server
      subscriptions:
        - name: BdoubleO100
          desc: ""
          url: http://www.youtube.com/feeds/videos.xml?channel_id=UClu2e7S8atp6tG2galK9hgg
        - name: cubfan135
          desc: ""
          url: http://www.youtube.com/feeds/videos.xml?channel_id=UC9lJXqw4QZw-HWaZH6sN-xw
        - name: docm77
          desc: "Grind, Optimize, Automate, Thrive!"
          url: http://www.youtube.com/feeds/videos.xml?channel_id=UC4O9HKe9Jt5yAhKuNv3LXpQ
        - name: EthosLab
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCFKDEp9si4RmHFWJW1vYsMA
        - name: FalseSymmetry
          desc: ""
          url: http://www.youtube.com/feeds/videos.xml?channel_id=UCuQYHhF6on6EXXO-_i_ClHQ
        - name: GeminiTay
          desc: ""
          url: http://www.youtube.com/feeds/videos.xml?channel_id=UCUBsjvdHcwZd3ztdY1Zadcw
        - name: Grian
          desc: "Please hold!"
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCR9Gcq0CMm6YgTzsDxAxjOQ
        - name: Hypnotizd
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UChi5MyXJLQuPni3dM19Ar3g
        - name: impulseSV
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCuMJPFqazQI4SofSFEd-5zA
        - name: iskall85
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCZ9x-z3iOnIbJxVpm1rsu2A
        - name: iJevin
          desc: "iJustine's relative"
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCrEtZMErQXaSYy_JDGoU5Qw
        - name: JoeHillsTSD
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCtWObtiLCNI_BTBHwEOZNqg
        - name: Keralis
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCcJgOennb0II4a_qi9OMkRA
        - name: Mumbo Jumbo
          desc: "His name is Mumbo Jumbo"
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UChFur_NwVSbUozOcF_F2kMg,
        - name: PearlescentMoon
          desc: "Why is your house mirord?"
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UC1GJ5aeqpEWklMBQ3oXrPQQ
        - name: rendog
          desc: "Doc's husband (at lest on the server)"
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCDpdtiUfcdUCzokpRWORRqA
        - name: GoodTimesWithScar
          desc: "HOTGUY!"
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCodkNmk9oWRTIYZdr_HuSlg
        - name: MCSkizzleman
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCYdXHOv7srjm-ZsNsTcwbBw
        - name: SmallishBeans
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UC4qdHN4zHhd4VvNy3zNgXPA
        - name: Stressmonster101
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UC24lkOxZYna9nlXYBcJ9B8Q
        - name: Tango Tek
          desc: "Mr. Decked Out"
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UC4YUKOBld2PoOLzk0YZ80lw
        - name: VintageBeef
          desc: "Mr. Salmon"
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCu17Sme-KE87ca9OTzP0p7g
        - name: Welsknight
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCKEJZ-dqIA03evnzEy1_owg
        - name: xBCrafted
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UC_MkjhQr_D_lGlO3uu-GxyA
        - name: xisumavoid
          desc: "JEFF SE MINION"
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCU9pX8hKcrx06XfOB-VQLdw
        - name: ZedaphPlays
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCPK5G4jeoVEbUp5crKJl6CQ
        - name: ZombieCleo
          desc: ""
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UCjI5qxhtyv3srhWr60HemRw
        - name: Hermitcraft Recap
          desc: "Welcome to the Hermitcraft Recap, my name is Pixelrifs, our writer is SloyXP, captions on this video were provided by Liarah."
          url: https://www.youtube.com/feeds/videos.xml?channel_id=UC32w6uX5qtmUtF4QQQ2PKaQ

    - name: Podcasts
      desc: Podcasts that I follow
